jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
       auto_detection: false
       directories:
           app:
               namespace_prefix: 'App\Entity'
               path: "%kernel.project_dir%/config/serializer"
